theme = "catppuccin_mocha"
[editor]
bufferline = "always"
[keys.normal]
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]

[keys.normal.space]
m = ':sh zellij run --floating --close-on-exit --name markdown -- mo "%{buffer_name}"'
G = ':sh gh browse "%{buffer_name}:%{cursor_line}" -c=%sh{git rev-parse HEAD}'
# line-number = "relative"
# mouse = false
#
# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"
#
# [editor.file-picker]
# hidden = false
