#!/bin/bash

ADDITIONAL_ARGS=$@
ALL_CLUSTERS=$(kubectl config get-contexts -o=name)
CLUSTER_FILTER=${CLUSTER_FILTER:-}
CLUSTERS=${CLUSTERS:=$ALL_CLUSTERS}

if [ ! -z "$CLUSTER_FILTER" ]; then
  CLUSTERS=$(echo "$CLUSTERS" | grep "$CLUSTER_FILTER")
fi

REDIRECT=${REDIRECT:=}

if [ ! -z "$REDIRECT"    -a  ! -d "$REDIRECT"  ]; then
  echo "error REDIRECT=$REDIRECT : directory deosn't exist"
  exit 1
fi

echo "Will execute command in clusters:"
echo "$CLUSTERS"

sleep 2

for context in $CLUSTERS; do
  echo "executing command: kubectl --context $context $ADDITIONAL_ARGS"
  if [ -z $REDIRECT ]; then
    kubectl --context $context $ADDITIONAL_ARGS
    printf "\n\n"
  else
    kubectl --context $context $ADDITIONAL_ARGS > $REDIRECT/output-$context.yaml
  fi
done
